### ISSUE TITLE
Running Step 1 Results in Error

### ISSUE THREAD

**Issue by cboecking** [lamini-ai/docs-to-qa#10]
Hi Team, 

Thank you for your great work! I am trying to get this example to function without success. I am getting an error on step 1. I have tried this on three different machines without success. Below are the important details:

# questions/comments:

* do I need to specify the model?
* I have read the readme from top to bottom. I do not see that I am missing anything.

# Latest OS
❯ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

# Docker works
❯ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
719385e32844: Pull complete
Digest: sha256:88ec0acaa3ec199d3b7eaf73588f4518c25f9d34f58ce9a0df68429c5af48e8d
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

# Results of generate_questions.sh (error)
❯ ./generate_questions.sh --docs_dirpath "data_small"
+++ dirname ./generate_questions.sh
++ cd .
++ pwd
+ LOCAL_DIRECTORY=/home/ubuntu/docs-to-qa
+ /home/ubuntu/docs-to-qa/scripts/build.sh
+++ dirname /home/ubuntu/docs-to-qa/scripts/build.sh
++ cd /home/ubuntu/docs-to-qa/scripts
++ pwd
+ LOCAL_DIRECTORY=/home/ubuntu/docs-to-qa/scripts
+ docker build -t docs_to_qa:latest /home/ubuntu/docs-to-qa/scripts/..
[+] Building 1.5s (12/12) FINISHED                                                                                                             docker:default
 => [internal] load build definition from Dockerfile                                                                                                     0.1s
 => => transferring dockerfile: 538B                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                        0.2s
 => => transferring context: 2B                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/python:3.11                                                                                           0.7s
 => [1/7] FROM docker.io/library/python:3.11@sha256:832cdc43284d265c5a5626893fbd0192c2878ef8381c9cc255fc26b93f6a28fd                                     0.0s
 => [internal] load build context                                                                                                                        0.1s
 => => transferring context: 3.79kB                                                                                                                      0.0s
 => CACHED [2/7] RUN apt-get -yq update && apt-get -yqq install libpq-dev psmisc                                                                         0.0s
 => CACHED [3/7] WORKDIR /app/docs_to_qa                                                                                                                 0.0s
 => CACHED [4/7] COPY ./requirements.txt /app/docs_to_qa/requirements.txt                                                                                0.0s
 => CACHED [5/7] RUN pip install -r requirements.txt                                                                                                     0.0s
 => CACHED [6/7] COPY . /app/docs_to_qa                                                                                                                  0.0s
 => CACHED [7/7] WORKDIR /app/docs_to_qa                                                                                                                 0.0s
 => exporting to image                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                  0.0s
 => => writing image sha256:a319b3c93754f9b380fc86e96f022120135f12ec120ed8fe5904523ff33cbfe1                                                             0.0s
 => => naming to docker.io/library/docs_to_qa:latest                                                                                                     0.0s
+ docker run -v /home/ubuntu/.powerml:/root/.powerml -v /home/ubuntu/docs-to-qa/data:/app/docs_to_qa/data -v /home/ubuntu/docs-to-qa/outputs:/app/docs_to_qa/outputs -it --rm --entrypoint /app/docs_to_qa/scripts/start-gen-ques.sh docs_to_qa:latest --docs_dirpath data_small
+++ dirname /app/docs_to_qa/scripts/start-gen-ques.sh
++ cd /app/docs_to_qa/scripts
++ pwd
+ LOCAL_DIRECTORY=/app/docs_to_qa/scripts
+ PYTHONPATH=/app/docs_to_qa/scripts/..
+ python3 /app/docs_to_qa/scripts/../docs_to_qa/cli/generate_questions.py --docs_dirpath data_small
Arguments parsed. Setting the arguments not passed to default. Arguments:
{'docs_dirpath': 'data_small', 'qa_path': None, 'model_name': None, 'question_system_prompt': None, 'question_prompt_suffix': None, 'start_index': 0, 'save': True, 'verbose': True}
Generating questions...
  0%|                                                                                                                                   | 0/1 [00:00<?, ?it/s]status code: 401
  0%|                                                                                                                                   | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llama/engine/lamini.py", line 257, in make_web_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.powerml.co/v2/lamini/completions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/docs_to_qa/scripts/../docs_to_qa/cli/generate_questions.py", line 38, in <module>
    main()
  File "/app/docs_to_qa/scripts/../docs_to_qa/cli/generate_questions.py", line 24, in main
    questions = run_prompt_engineer_questions(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/docs_to_qa/docs_to_qa.py", line 516, in run_prompt_engineer_questions
    questions = llm.prompt_engineer_questions(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/docs_to_qa/docs_to_qa.py", line 331, in prompt_engineer_questions
    self._run_questions(start_index=start_index, save=save, verbose=verbose)
  File "/usr/local/lib/python3.11/site-packages/llama/docs_to_qa/docs_to_qa.py", line 238, in _run_questions
    output = self.question_llm(prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/runners/basic_model_runner.py", line 52, in __call__
    output_objects = self.llm(
                     ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/engine/typed_lamini.py", line 13, in __call__
    result = super().__call__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/engine/lamini.py", line 83, in __call__
    return self.make_web_request(url, "post", req_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/engine/lamini.py", line 277, in make_web_request
    raise AuthenticationError(
llama.error.error.AuthenticationError: Invalid token

**Comment by greg1232** [comment]
Thanks for trying this out and reporting.  Please get an API token and add it to your config file as described in: 

https://lamini-ai.github.io/Start/auth/
