### ISSUE TITLE
Step 1 Results in Errors

### ISSUE THREAD

**Issue by eobdam** [lamini-ai/docs-to-qa#11]
+++ dirname /app/docs_to_qa/scripts/start-gen-ques.sh
++ cd /app/docs_to_qa/scripts
++ pwd
+ LOCAL_DIRECTORY=/app/docs_to_qa/scripts
+ PYTHONPATH=/app/docs_to_qa/scripts/..
+ python3 /app/docs_to_qa/scripts/../docs_to_qa/cli/generate_questions.py --docs_dirpath data_small
Traceback (most recent call last):
  File "/app/docs_to_qa/scripts/../docs_to_qa/cli/generate_questions.py", line 1, in <module>
    from llama import run_prompt_engineer_questions
ImportError: cannot import name 'run_prompt_engineer_questions' from 'llama' (/usr/local/lib/python3.11/site-packages/llama/__init__.py)

**Comment by eobdam** [comment]
Changing requirements.txt to earlier version 1.0.3 of lamini (lamini==1.0.3) solves the previous error but gives the following:
+++ dirname /app/docs_to_qa/scripts/start-gen-ques.sh
++ cd /app/docs_to_qa/scripts
++ pwd
+ LOCAL_DIRECTORY=/app/docs_to_qa/scripts
+ PYTHONPATH=/app/docs_to_qa/scripts/..
+ python3 /app/docs_to_qa/scripts/../docs_to_qa/cli/generate_questions.py --docs_dirpath data_small
Arguments parsed. Setting the arguments not passed to default. Arguments:
{'docs_dirpath': 'data_small', 'qa_path': None, 'model_name': None, 'question_system_prompt': None, 'question_prompt_suffix': None, 'start_index': 0, 'save': True, 'verbose': True}
Generating questions...
  0%|                                                                                                                       | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llama/program/util/run_ai.py", line 45, in make_web_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.lamini.ai/v2/lamini/completions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/docs_to_qa/scripts/../docs_to_qa/cli/generate_questions.py", line 38, in <module>
    main()
  File "/app/docs_to_qa/scripts/../docs_to_qa/cli/generate_questions.py", line 24, in main
    questions = run_prompt_engineer_questions(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/docs_to_qa/docs_to_qa.py", line 489, in run_prompt_engineer_questions
    questions = llm.prompt_engineer_questions(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/docs_to_qa/docs_to_qa.py", line 304, in prompt_engineer_questions
    self._run_questions(start_index=start_index, save=save, verbose=verbose)
  File "/usr/local/lib/python3.11/site-packages/llama/docs_to_qa/docs_to_qa.py", line 211, in _run_questions
    output = self.question_llm(prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/runners/runner.py", line 16, in __call__
    return self.call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/runners/basic_model_runner.py", line 50, in call
    output_objects = self.llm(
                     ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/engine/typed_lamini.py", line 13, in __call__
    result = super().__call__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/engine/lamini.py", line 110, in __call__
    return make_web_request("post", url, self.api_key, req_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/program/util/run_ai.py", line 52, in make_web_request
    raise ModelNameError(json_response.get("detail", "ModelNameError"))
llama.error.error.ModelNameError: Not Found

Looks like example on website is not maintained and/or previous api no longer supported?

**Comment by creatorcao** [comment]
I got the same error. Is there any solution? Thank you.
