### ISSUE TITLE
Authenticatation error when running in GitHub Code Spaces.

### ISSUE THREAD

**Issue by karthigb** [lamini-ai/docs-to-qa#9]
I'm trying to run the demo script in code spaces, but I keep getting the error below. I couldn't find a place in the code that referenced an API authentication key.

How do I use my own Lamini API key to try this out?

**Error**:
`llama.error.error.AuthenticationError: Invalid token`

**Full stack trace**:
`$ ./run.sh \
> --question "When did H. CON. RES. 1 pass?" \
> --model_name "0eb43acdd0d81f06647dfe81a1033740255c6138cc8e0a816f1308e3c784cbb9"
+++ dirname ./run.sh
++ cd .
++ pwd
+ LOCAL_DIRECTORY=/workspaces/docs-to-qa
+ /workspaces/docs-to-qa/scripts/build.sh
+++ dirname /workspaces/docs-to-qa/scripts/build.sh
++ cd /workspaces/docs-to-qa/scripts
++ pwd
+ LOCAL_DIRECTORY=/workspaces/docs-to-qa/scripts
+ docker build -t docs_to_qa:latest /workspaces/docs-to-qa/scripts/..
[+] Building 76.9s (13/13) FINISHED                                                                                                    docker:default
 => [internal] load build definition from Dockerfile                                                                                             0.4s
 => => transferring dockerfile: 538B                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                0.5s
 => => transferring context: 2B                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/python:3.11                                                                                   1.7s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                    0.0s
 => [1/7] FROM docker.io/library/python:3.11@sha256:652c9f890a7f38bab4d67ee95c54d72955792623122cfea0a87aa74d927e41ae                            23.7s
 => => resolve docker.io/library/python:3.11@sha256:652c9f890a7f38bab4d67ee95c54d72955792623122cfea0a87aa74d927e41ae                             0.2s
 => => sha256:652c9f890a7f38bab4d67ee95c54d72955792623122cfea0a87aa74d927e41ae 2.14kB / 2.14kB                                                   0.0s
 => => sha256:ebe56d7878f2a4fbf42db4aa4d169ed17da3b3365244dbb46ec1b237de45df80 2.01kB / 2.01kB                                                   0.0s
 => => sha256:de90e45b6a7d72a82fc041ee87b8a18f7bf8725b186e62cb15d73e13c92a1b74 7.53kB / 7.53kB                                                   0.0s
 => => sha256:800d84653581fc119cd75cd572fa190d3b813d49221b9e5ee463e3560e2cb342 64.13MB / 64.13MB                                                 1.2s
 => => sha256:0a9573503463fd3166b5b1f34a7720dac28609e98d731e50e7068f92e79b8545 49.58MB / 49.58MB                                                 1.5s
 => => sha256:1ccc26d841b4acc2562483bf393ce1cf8bc358ced09ccd825425226827c79c92 24.05MB / 24.05MB                                                 0.8s
 => => sha256:7c632e57ea62ea950c367f484f52cdcfd2adb12060a31f5c413f40db9822e96e 211.06MB / 211.06MB                                               5.2s
 => => sha256:f9a1922eee8a7d8ea8d227102bf5b6671dd4f68a152a438c803c54092410bb28 6.39MB / 6.39MB                                                   1.7s
 => => sha256:ebb263a37449b31ecf00c4402b8028ac00a06b66d4d7e1ae29b95c7bec6fe30c 19.80MB / 19.80MB                                                 2.1s
 => => sha256:46a466baf7786e89de5b29fdd1199d01a89d8d6b0ae5472a028c5191e9f2bedc 244B / 244B                                                       1.9s
 => => extracting sha256:0a9573503463fd3166b5b1f34a7720dac28609e98d731e50e7068f92e79b8545                                                        3.3s
 => => sha256:5bb253f012e0c25e278ca32e2be2129e9dab97e089f7fbeedb4834bb273f3419 3.11MB / 3.11MB                                                   2.2s
 => => extracting sha256:1ccc26d841b4acc2562483bf393ce1cf8bc358ced09ccd825425226827c79c92                                                        0.6s
 => => extracting sha256:800d84653581fc119cd75cd572fa190d3b813d49221b9e5ee463e3560e2cb342                                                        2.8s
 => => extracting sha256:7c632e57ea62ea950c367f484f52cdcfd2adb12060a31f5c413f40db9822e96e                                                        8.5s
 => => extracting sha256:f9a1922eee8a7d8ea8d227102bf5b6671dd4f68a152a438c803c54092410bb28                                                        0.3s
 => => extracting sha256:ebb263a37449b31ecf00c4402b8028ac00a06b66d4d7e1ae29b95c7bec6fe30c                                                        0.6s
 => => extracting sha256:46a466baf7786e89de5b29fdd1199d01a89d8d6b0ae5472a028c5191e9f2bedc                                                        0.0s
 => => extracting sha256:5bb253f012e0c25e278ca32e2be2129e9dab97e089f7fbeedb4834bb273f3419                                                        0.2s
 => [internal] load build context                                                                                                                0.4s
 => => transferring context: 3.18MB                                                                                                              0.1s
 => [2/7] RUN apt-get -yq update && apt-get -yqq install libpq-dev psmisc                                                                        4.4s
 => [3/7] WORKDIR /app/docs_to_qa                                                                                                                0.3s
 => [4/7] COPY ./requirements.txt /app/docs_to_qa/requirements.txt                                                                               0.3s
 => [5/7] RUN pip install -r requirements.txt                                                                                                   31.7s
 => [6/7] COPY . /app/docs_to_qa                                                                                                                 0.4s
 => [7/7] WORKDIR /app/docs_to_qa                                                                                                                0.3s
 => exporting to image                                                                                                                          13.5s
 => => exporting layers                                                                                                                         13.5s
 => => writing image sha256:632b687fc3b810faaa67f5a1419cb7c7bb8f61a47a84ee9ac50287d57e95293d                                                     0.0s
 => => naming to docker.io/library/docs_to_qa:latest                                                                                             0.0s
+ docker run -v /home/codespace/.powerml:/root/.powerml -v /workspaces/docs-to-qa/data:/app/docs_to_qa/data -v /workspaces/docs-to-qa/outputs:/app/docs_to_qa/outputs -it --rm --entrypoint /app/docs_to_qa/scripts/start-run.sh docs_to_qa:latest --question 'When did H. CON. RES. 1 pass?' --model_name 0eb43acdd0d81f06647dfe81a1033740255c6138cc8e0a816f1308e3c784cbb9
+++ dirname /app/docs_to_qa/scripts/start-run.sh
++ cd /app/docs_to_qa/scripts
++ pwd
+ LOCAL_DIRECTORY=/app/docs_to_qa/scripts
+ PYTHONPATH=/app/docs_to_qa/scripts/..
+ python3 /app/docs_to_qa/scripts/../docs_to_qa/cli/run.py --question 'When did H. CON. RES. 1 pass?' --model_name 0eb43acdd0d81f06647dfe81a1033740255c6138cc8e0a816f1308e3c784cbb9
=============PROMPT================
<s>[INST] <<SYS>>
You are an assistant who answers questions and holds a conversation. You are helpful and friendly.
<</SYS>>

When did H. CON. RES. 1 pass? [/INST]
status code: 401
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llama/engine/lamini.py", line 253, in make_web_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.powerml.co/v2/lamini/completions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/docs_to_qa/scripts/../docs_to_qa/cli/run.py", line 30, in <module>
    main()
  File "/app/docs_to_qa/scripts/../docs_to_qa/cli/run.py", line 21, in main
    output = run_model(
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/docs_to_qa/docs_to_qa.py", line 608, in run_model
    output = llm.run(question, doc_id, verbose=verbose)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/docs_to_qa/docs_to_qa.py", line 139, in run
    output = self.qa_llm(prompt)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/runners/basic_model_runner.py", line 52, in __call__
    output_objects = self.llm(
                     ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/engine/typed_lamini.py", line 13, in __call__
    result = super().__call__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/engine/lamini.py", line 81, in __call__
    return self.make_web_request(url, "post", req_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama/engine/lamini.py", line 273, in make_web_request
    raise AuthenticationError(
llama.error.error.AuthenticationError: Invalid token`

**Comment by karthigb** [comment]
Update: I'm not getting a 500 error after creating a yaml with my API key as per: https://lamini-ai.github.io/Start/auth/
